version: "3.9"

services:
  db:
    image: tayokanch/postgres:16
    container_name: notewatch-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - note-watch-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      retries: 5
      start_period: 10s

  notewatchapi_v1:
    build: .
    container_name: notewatchapi_v1
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
      API_PORT: 3000
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "3000"
    networks:
      - note-watch-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health || exit 1"]
      interval: 5s
      retries: 5
      start_period: 5s

  notewatchapi_v2:
    build: .
    container_name: notewatchapi_v2
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
      API_PORT: 3001
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "3001"
    networks:
      - note-watch-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health || exit 1"]
      interval: 5s
      retries: 5
      start_period: 5s

  notewatchapi_v3:
    build: .
    container_name: notewatchapi_v3
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
      API_PORT: 3002
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "3002"
    networks:
      - note-watch-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health || exit 1"]
      interval: 5s
      retries: 5
      start_period: 5s

  nginx:
    image: nginx:1.28.1
    container_name: notewatch-nginx-server
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      notewatchapi_v1:
        condition: service_healthy
      notewatchapi_v2:
        condition: service_healthy
      notewatchapi_v3:
        condition: service_healthy
    restart: always
    networks:
      - note-watch-network

volumes:
  pgdata:

networks:
  note-watch-network:
    driver: bridge
