version: "3.9"

services:
  db:
    image: tayokanch/postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - note-watch-network

  nginx:
    image: nginx:1.28.1
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - notewatchapi_v1
      - notewatchapi_v2
      - notewatchapi_v3
    restart: always
    networks:
      - note-watch-network

  notewatchapi_v1:
    build: .
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
    depends_on:
      - db
    expose:
      - "3000"
    networks:
      - note-watch-network
    restart: always

  notewatchapi_v2:
    build: .
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
    depends_on:
      - db
    expose:
      - "3001"
    networks:
      - note-watch-network
    restart: always

  notewatchapi_v3:
    build: .
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
    depends_on:
      - db
    expose:
      - "3002"
    networks:
      - note-watch-network
    restart: always

volumes:
  pgdata:

networks:
  note-watch-network:
    driver: bridge
