name: notewatch

services:
  # -----------------------
  # PostgreSQL Database
  # -----------------------
  db:
    image: tayokanch/postgres:16
    container_name: notewatch-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    expose:
      - ${DB_PORT}
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migration:/docker-entrypoint-initdb.d
    networks:
      - notewatch_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      retries: 5
      start_period: 10s

  # -----------------------
  # Notewatch API Instances
  # -----------------------
  notewatchapi_v1:
    build: .
    container_name: notewatchapi_v1
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      INIT_ADMIN_EMAIL: $(INIT_ADMIN_EMAIL)
      DB_PORT: 5432
      API_PORT: 3000
      JWT_SECRET: $(JWT_SECRET)
    expose:
      - "3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - notewatch_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:3000/health || exit 1"]
      interval: 5s
      retries: 5
      start_period: 20s

  notewatchapi_v2:
    build: .
    container_name: notewatchapi_v2
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: $(JWT_SECRET)
      INIT_ADMIN_EMAIL: $(INIT_ADMIN_EMAIL)
      DB_PORT: 5432
      API_PORT: 3001
    expose:
      - "3001"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - notewatch_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:3001/health || exit 1"]
      interval: 5s
      retries: 5
      start_period: 20s

  notewatchapi_v3:
    build: .
    container_name: notewatchapi_v3
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: $(JWT_SECRET)
      INIT_ADMIN_EMAIL: $(INIT_ADMIN_EMAIL)
      DB_PORT: 5432
      API_PORT: 3002
    expose:
      - "3002"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - notewatch_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:3002/health || exit 1"]
      interval: 5s
      retries: 5
      start_period: 20s
# -----------------------
# Volumes
# -----------------------
volumes:
  pgdata:

# -----------------------
# Networks
# -----------------------
networks:
  notewatch_network:
    external: true

